Form post request
mam249/step pull request #6
Opened 2020-07-21 15:44 UTC by mam249

wasn't sure if this is how you're meant to resolve nits but I just added it in as an extra commit here

2020-07-21 16:32 UTC, lminchillo commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    }
```suggestion
    if (anonymous || displayName == "") {
        displayName = "Anonymous";
    }
```

2020-07-21 16:36 UTC, lminchillo commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    boolean anonymous = Boolean.parseBoolean(getParameter(request, "anonymous", "false"));
false (no quotes)

2020-07-21 16:37 UTC, lminchillo requested changes
LGTM after replacing "false" with false

2020-07-22 09:44 UTC, mam249 commented
when I replace "false" with false the getParameter function stops working - I took the function as is from one of the examples

2020-07-23 12:04 UTC, lminchillo commented
> when I replace "false" with false the getParameter function stops working - I took the function as is from one of the examples

Oh ok I got it now. It's because parseBoolean accepts a String so that's actually correct. My bad!

2020-07-23 12:06 UTC, lminchillo commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
>    private String json_array;
Please change to camel case

https://google.github.io/styleguide/javaguide.html#s5.2.7-local-variable-names

2020-07-23 12:07 UTC, lminchillo approved these changes
LGTM!

2020-07-23 14:10 UTC, merged